// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCHYAYB7u8QCbfvNgA2XsxmUZYHtiLrCAE',
    appId: '1:207833854752:web:0e8dbc6f6581c82a8add45',
    messagingSenderId: '207833854752',
    projectId: 'rolebased-b5e93',
    authDomain: 'rolebased-b5e93.firebaseapp.com',
    storageBucket: 'rolebased-b5e93.appspot.com',
    measurementId: 'G-C5RB2BT125',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCGOyXLhspvz2V4wgjGq13Fnpf5EX5CEvc',
    appId: '1:207833854752:android:e21daba37b9dc9228add45',
    messagingSenderId: '207833854752',
    projectId: 'rolebased-b5e93',
    storageBucket: 'rolebased-b5e93.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC1XZVIFBvTb1z3-M4ebIqtPnutlnQsYR4',
    appId: '1:207833854752:ios:501f3354e279efbb8add45',
    messagingSenderId: '207833854752',
    projectId: 'rolebased-b5e93',
    storageBucket: 'rolebased-b5e93.appspot.com',
    iosBundleId: 'com.example.rolebased',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC1XZVIFBvTb1z3-M4ebIqtPnutlnQsYR4',
    appId: '1:207833854752:ios:501f3354e279efbb8add45',
    messagingSenderId: '207833854752',
    projectId: 'rolebased-b5e93',
    storageBucket: 'rolebased-b5e93.appspot.com',
    iosBundleId: 'com.example.rolebased',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCHYAYB7u8QCbfvNgA2XsxmUZYHtiLrCAE',
    appId: '1:207833854752:web:da45cee6a47333448add45',
    messagingSenderId: '207833854752',
    projectId: 'rolebased-b5e93',
    authDomain: 'rolebased-b5e93.firebaseapp.com',
    storageBucket: 'rolebased-b5e93.appspot.com',
    measurementId: 'G-XCF9SJE2PG',
  );
}
